name: Update Cloudflare Public IP

on:
  push:
    branches:
      - main
      - feat/add_workflow
  workflow_dispatch:


jobs:
  run-py:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run:
          pip install requests
          pip install os
      - name: run python Script
        run: python3 pubip_updater.py
