name: Update Cloudflare Public IP

on:
  schedule:
    - cron: '0 0 * * *'


jobs:
  run-py:
    runs-on: self-hosted
    timeout-minutes: 120
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          source /home/ianl303/github-actions/update_pubip/bin/activate 
          python3 -m pip install requests
      - name: run python Script
        env:
          CLOUDFLARE_TOKEN: ${{secrets.CLOUDFLARE_TOKEN}}
        run: |
          python3 pubip_updater.py
      - name: Cleanup
        run: |
          source /home/ianl303/github-actions/update_pubip/bin/activate
          deactivate