name: Update Cloudflare Public IP

on:
  push:
    branches:
      - main
      - feat/add_workflow
  workflow_dispatch:


jobs:
  run-py:
    runs-on: self-hosted
    steps:
      - name: run python Script
        run: python pubip_updater.py
