name: Update Cloudflare Public IP

on:
  push:
    branches:
      - main
      - feat/add_workflow
  workflow_dispatch:


jobs:
  run-py:
    runs-on: self-hosted
    env:
      CLOUDFLARE_TOKEN: ${{secrets.CLOUDFLARE_TOKEN}}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          source /home/ianl303/github-actions/update_pubip/bin/activate 
          python3 -m pip install requests
#          python3 -m pip install os_sys
      - name: run python Script
        env:
          CLOUDFLARE_TOKEN: ${{secrets.CLOUDFLARE_TOKEN}}
        run: |
          echo "$CLOUDFLARE_TOKEN"
#          python3 pubip_updater.py
      - name: Cleanup
        run: |
          deactivate